/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tijana
 */
public class Konfiguracija extends javax.swing.JDialog {

    /**
     * Creates new form Konfiguracija
     *
     * @param parent
     * @param modal
     */
    public Konfiguracija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }

        initComponents();

        unesiPodatke();
        this.setTitle("Konfiguracija");
        this.setSize(330, 168);
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Port:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 92, -1));

        jLabelPort.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPort.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, 25));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Konfiguracija.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void unesiPodatke() {

        String putanja = "konfiguracija/Konfiguracija_klijent.properties";

        Properties p = new Properties();

        try (FileInputStream fis = new FileInputStream(putanja)) {
            p.load(fis);

            try {
                int port = Integer.parseInt(p.getProperty("Port"));
                jLabelPort.setText(String.valueOf(port));
            } catch (NumberFormatException numberFormatException) {
                System.err.println("Broj porta nije dat u ispravnom formatu.");

            }
        } catch (IOException e) {
            System.err.println("Greška pri učitavanju konfiguracionog fajla. " + e);

        }

    }

}
