/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Polaznik;
import model.UzrasnaKategorija;

/**
 *
 * @author Tijana
 */
public class KreirajPolaznika extends javax.swing.JDialog {

    private GlavnaForma gf;
    private Polaznik polaznik;

    public Polaznik getPolaznik() {
        return polaznik;
    }

    public void setPolaznik(Polaznik polaznik) {
        this.polaznik = polaznik;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public void setjButtonObrisi(JButton jButtonObrisi) {
        this.jButtonObrisi = jButtonObrisi;
    }

    public JButton getjButtonObrisiPolaznika() {
        return jButtonObrisiPolaznika;
    }

    public void setjButtonObrisiPolaznika(JButton jButtonObrisiPolaznika) {
        this.jButtonObrisiPolaznika = jButtonObrisiPolaznika;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public void setjButtonOdustani(JButton jButtonOdustani) {
        this.jButtonOdustani = jButtonOdustani;
    }

    public JButton getjButtonPrikaziObrisi() {
        return jButtonPrikaziObrisi;
    }

    public void setjButtonPrikaziObrisi(JButton jButtonPrikaziObrisi) {
        this.jButtonPrikaziObrisi = jButtonPrikaziObrisi;
    }

    public JButton getjButtonPrikaziPromeni() {
        return jButtonPrikaziPromeni;
    }

    public void setjButtonPrikaziPromeni(JButton jButtonPrikaziPromeni) {
        this.jButtonPrikaziPromeni = jButtonPrikaziPromeni;
    }

    public JButton getjButtonPromeniPolaznika() {
        return jButtonPromeniPolaznika;
    }

    public void setjButtonPromeniPolaznika(JButton jButtonPromeniPolaznika) {
        this.jButtonPromeniPolaznika = jButtonPromeniPolaznika;
    }

    public JButton getjButtonSacuvaj() {
        return jButtonSacuvaj;
    }

    public void setjButtonSacuvaj(JButton jButtonSacuvaj) {
        this.jButtonSacuvaj = jButtonSacuvaj;
    }

    public JButton getjButtonZapamti() {
        return jButtonZapamti;
    }

    public void setjButtonZapamti(JButton jButtonZapamti) {
        this.jButtonZapamti = jButtonZapamti;
    }

    public JComboBox<UzrasnaKategorija> getjComboBoxUzrast() {
        return jComboBoxUzrast;
    }

    public void setjComboBoxUzrast(JComboBox<UzrasnaKategorija> jComboBoxUzrast) {
        this.jComboBoxUzrast = jComboBoxUzrast;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    public void setjTextFieldIme(JTextField jTextFieldIme) {
        this.jTextFieldIme = jTextFieldIme;
    }

    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }

    public void setjTextFieldPrezime(JTextField jTextFieldPrezime) {
        this.jTextFieldPrezime = jTextFieldPrezime;
    }

    /**
     * Creates new form KreirajPolaznik
     *
     * @param parent
     * @param modal
     * @param polaznik
     */
    public KreirajPolaznika(java.awt.Frame parent, boolean modal, Polaznik polaznik) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(570, 445);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Kreiraj polaznika");

        this.gf = (GlavnaForma) parent;
        this.polaznik = polaznik;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonOdustani = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxUzrast = new javax.swing.JComboBox<>();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldIme = new javax.swing.JTextField();
        jButtonPromeniPolaznika = new javax.swing.JButton();
        jButtonObrisiPolaznika = new javax.swing.JButton();
        jButtonPrikaziObrisi = new javax.swing.JButton();
        jButtonPrikaziPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POLAZNIK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 26, 110, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 217, 107, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOdustani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOdustani.setForeground(new java.awt.Color(0, 102, 153));
        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 140, 30));

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonZapamti.setForeground(new java.awt.Color(0, 102, 153));
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonZapamti, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 140, 30));

        jButtonSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 153));
        jButtonSacuvaj.setText("Sačuvaj promene");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 140, 30));

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Uzrasna kategorija:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 150, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-mail adresa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 93, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prezime:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 64, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ime:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 37, 30));

        jPanel1.add(jComboBoxUzrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 310, 29));
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 310, 29));
        jPanel1.add(jTextFieldPrezime, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 310, 29));

        jTextFieldIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIme, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 310, 29));

        jButtonPromeniPolaznika.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPromeniPolaznika.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPromeniPolaznika.setText("Promeni polaznika");
        jButtonPromeniPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniPolaznikaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPromeniPolaznika, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 30));

        jButtonObrisiPolaznika.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisiPolaznika.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisiPolaznika.setText("Obriši polaznika");
        jButtonObrisiPolaznika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiPolaznikaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisiPolaznika, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 30));

        jButtonPrikaziObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziObrisi.setText("Prikaži polaznika");
        jButtonPrikaziObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 30));

        jButtonPrikaziPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziPromeni.setText("Prikaži polaznika");
        jButtonPrikaziPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jTextFieldImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImeActionPerformed

    private void jButtonPromeniPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniPolaznikaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPromeniPolaznikaActionPerformed

    private void jButtonObrisiPolaznikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiPolaznikaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiPolaznikaActionPerformed

    private void jButtonPrikaziObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziObrisiActionPerformed

    private void jButtonPrikaziPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPromeniActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziPromeniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonObrisiPolaznika;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPrikaziObrisi;
    private javax.swing.JButton jButtonPrikaziPromeni;
    private javax.swing.JButton jButtonPromeniPolaznika;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JComboBox<model.UzrasnaKategorija> jComboBoxUzrast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    public void ZapamtiAddActionListeners(ActionListener actionListener) {
        jButtonZapamti.addActionListener(actionListener);
    }

    public void PromeniAddActionListeners(ActionListener actionListener) {
        jButtonSacuvaj.addActionListener(actionListener);
    }

    public void ObrisiAddActionListeners(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }

    public void OdustaniAddActionListeners(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }

    public void ObrisiPolaznikaAddActionListeners(ActionListener actionListener) {
        jButtonObrisiPolaznika.addActionListener(actionListener);
    }

    public void PrikaziPromeniAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziPromeni.addActionListener(actionListener);
    }

    public void PrikaziObrisiAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziObrisi.addActionListener(actionListener);
    }

    public void PromeniPolaznikaAddActionListeners(ActionListener actionListener) {
        jButtonPromeniPolaznika.addActionListener(actionListener);
    }

}
