/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.UzrasnaKategorija;

/**
 *
 * @author Tijana
 */
public class KreirajUzrasnuKategoriju extends javax.swing.JDialog {

    private GlavnaForma gf;
    private UzrasnaKategorija uzrast;

    public UzrasnaKategorija getUzrast() {
        return uzrast;
    }

    public void setUzrast(UzrasnaKategorija uzrast) {
        this.uzrast = uzrast;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public void setjButtonObrisi(JButton jButtonObrisi) {
        this.jButtonObrisi = jButtonObrisi;
    }

    public JButton getjButtonObrisiKategoriju() {
        return jButtonObrisiKategoriju;
    }

    public void setjButtonObrisiKategoriju(JButton jButtonObrisiKategoriju) {
        this.jButtonObrisiKategoriju = jButtonObrisiKategoriju;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public void setjButtonOdustani(JButton jButtonOdustani) {
        this.jButtonOdustani = jButtonOdustani;
    }

    public JButton getjButtonPrikaziObrisi() {
        return jButtonPrikaziObrisi;
    }

    public void setjButtonPrikaziObrisi(JButton jButtonPrikaziObrisi) {
        this.jButtonPrikaziObrisi = jButtonPrikaziObrisi;
    }

    public JButton getjButtonPrikaziPromeni() {
        return jButtonPrikaziPromeni;
    }

    public void setjButtonPrikaziPromeni(JButton jButtonPrikaziPromeni) {
        this.jButtonPrikaziPromeni = jButtonPrikaziPromeni;
    }

    public JButton getjButtonPromeni() {
        return jButtonPromeni;
    }

    public void setjButtonPromeni(JButton jButtonPromeni) {
        this.jButtonPromeni = jButtonPromeni;
    }

    public JButton getjButtonSacuvaj() {
        return jButtonSacuvaj;
    }

    public void setjButtonSacuvaj(JButton jButtonSacuvaj) {
        this.jButtonSacuvaj = jButtonSacuvaj;
    }

    public JButton getjButtonZapamti() {
        return jButtonZapamti;
    }

    public void setjButtonZapamti(JButton jButtonZapamti) {
        this.jButtonZapamti = jButtonZapamti;
    }

    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    public JTextField getjTextFieldOpsegGodina() {
        return jTextFieldOpsegGodina;
    }

    public void setjTextFieldOpsegGodina(JTextField jTextFieldOpsegGodina) {
        this.jTextFieldOpsegGodina = jTextFieldOpsegGodina;
    }

    /**
     * Creates new form KreirajUzrast
     * @param parent
     * @param modal
     * @param uzrast
     */
    public KreirajUzrasnuKategoriju(java.awt.Frame parent, boolean modal, UzrasnaKategorija uzrast) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(418, 316);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Kreiraj uzrasnu kategoriju");

        this.gf = (GlavnaForma) parent;
        this.uzrast = uzrast;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonOdustani = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldOpsegGodina = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPromeni = new javax.swing.JButton();
        jButtonObrisiKategoriju = new javax.swing.JButton();
        jButtonPrikaziObrisi = new javax.swing.JButton();
        jButtonPrikaziPromeni = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonOdustani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOdustani.setForeground(new java.awt.Color(0, 102, 153));
        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 30));

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonZapamti.setForeground(new java.awt.Color(0, 102, 153));
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonZapamti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, 30));

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, 30));

        jButtonSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 153));
        jButtonSacuvaj.setText("Sačuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 80, 30));
        jPanel1.add(jTextFieldNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, 29));
        jPanel1.add(jTextFieldOpsegGodina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Opseg godina:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Naziv:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 140, 80, 30));

        jButtonPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPromeni.setText("Promeni kategoriju");
        jButtonPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, -1));

        jButtonObrisiKategoriju.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisiKategoriju.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisiKategoriju.setText("Obriši kategoriju");
        jButtonObrisiKategoriju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiKategorijuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisiKategoriju, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, -1));

        jButtonPrikaziObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziObrisi.setText("Prikaži kategoriju");
        jButtonPrikaziObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, -1));

        jButtonPrikaziPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziPromeni.setText("Prikaži kategoriju");
        jButtonPrikaziPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UZRASNA KATEGORIJA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 29, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPromeniActionPerformed

    private void jButtonObrisiKategorijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiKategorijuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiKategorijuActionPerformed

    private void jButtonPrikaziObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziObrisiActionPerformed

    private void jButtonPrikaziPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPromeniActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziPromeniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonObrisiKategoriju;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPrikaziObrisi;
    private javax.swing.JButton jButtonPrikaziPromeni;
    private javax.swing.JButton jButtonPromeni;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldOpsegGodina;
    // End of variables declaration//GEN-END:variables

    public void ZapamtiAddActionListeners(ActionListener actionListener) {
        jButtonZapamti.addActionListener(actionListener);
    }

    public void PromeniAddActionListeners(ActionListener actionListener) {
        jButtonSacuvaj.addActionListener(actionListener);
    }

    public void ObrisiAddActionListeners(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }

    public void OdustaniAddActionListeners(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }

    public void PromeniUzrasnuKategorijuAddActionListeners(ActionListener actionListener) {
        jButtonPromeni.addActionListener(actionListener);
    }

    public void PrikaziPromeniAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziPromeni.addActionListener(actionListener);
    }

    public void ObrisiUzrasnuKategorijuAddActionListeners(ActionListener actionListener) {
        jButtonObrisiKategoriju.addActionListener(actionListener);
    }

    public void PrikaziObrisiAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziObrisi.addActionListener(actionListener);
    }

}
