/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Kvalifikacija;

/**
 *
 * @author Tijana
 */
public class KreirajKvalifikaciju extends javax.swing.JDialog {

    private GlavnaForma gf;

    private Kvalifikacija kvalifikacija;

    public Kvalifikacija getKvalifikacija() {
        return kvalifikacija;
    }

    public void setKvalifikacija(Kvalifikacija kvalifikacija) {
        this.kvalifikacija = kvalifikacija;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public void setjButtonObrisi(JButton jButtonObrisi) {
        this.jButtonObrisi = jButtonObrisi;
    }

    public JButton getjButtonObrisiKvalifikaciju() {
        return jButtonObrisiKvalifikaciju;
    }

    public void setjButtonObrisiKvalifikaciju(JButton jButtonObrisiKvalifikaciju) {
        this.jButtonObrisiKvalifikaciju = jButtonObrisiKvalifikaciju;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public void setjButtonOdustani(JButton jButtonOdustani) {
        this.jButtonOdustani = jButtonOdustani;
    }

    public JButton getjButtonPrikaziObrisi() {
        return jButtonPrikaziObrisi;
    }

    public void setjButtonPrikaziObrisi(JButton jButtonPrikaziObrisi) {
        this.jButtonPrikaziObrisi = jButtonPrikaziObrisi;
    }

    public JButton getjButtonPrikaziPromeni() {
        return jButtonPrikaziPromeni;
    }

    public void setjButtonPrikaziPromeni(JButton jButtonPrikaziPromeni) {
        this.jButtonPrikaziPromeni = jButtonPrikaziPromeni;
    }

    public JButton getjButtonPromeni() {
        return jButtonPromeni;
    }

    public void setjButtonPromeni(JButton jButtonPromeni) {
        this.jButtonPromeni = jButtonPromeni;
    }

    public JButton getjButtonSacuvaj() {
        return jButtonSacuvaj;
    }

    public void setjButtonSacuvaj(JButton jButtonSacuvaj) {
        this.jButtonSacuvaj = jButtonSacuvaj;
    }

    public JButton getjButtonZapamti() {
        return jButtonZapamti;
    }

    public void setjButtonZapamti(JButton jButtonZapamti) {
        this.jButtonZapamti = jButtonZapamti;
    }

    public JTextField getjTextFieldOrganizacija() {
        return jTextFieldOrganizacija;
    }

    public void setjTextFieldOrganizacija(JTextField jTextFieldOrganizacija) {
        this.jTextFieldOrganizacija = jTextFieldOrganizacija;
    }

    public JTextField getjTextFieldTip() {
        return jTextFieldTip;
    }

    public void setjTextFieldTip(JTextField jTextFieldTip) {
        this.jTextFieldTip = jTextFieldTip;
    }

    /**
     * Creates new form KreirajKvalifikacija
     * @param parent
     * @param modal
     * @param kvalifikacija
     */
    public KreirajKvalifikaciju(java.awt.Frame parent, boolean modal, Kvalifikacija kvalifikacija) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(642, 346);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Kreiraj kvalifikaciju");

        this.gf = (GlavnaForma) parent;
        this.kvalifikacija = kvalifikacija;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTip = new javax.swing.JTextField();
        jButtonObrisi = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldOrganizacija = new javax.swing.JTextField();
        jButtonPromeni = new javax.swing.JButton();
        jButtonPrikaziPromeni = new javax.swing.JButton();
        jButtonObrisiKvalifikaciju = new javax.swing.JButton();
        jButtonPrikaziObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KVALIFIKACIJA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 149, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tip kvalifikacije:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 30));

        jTextFieldTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTipActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 428, 29));

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 100, 30));

        jButtonSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 153));
        jButtonSacuvaj.setText("Sačuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 100, 30));

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonZapamti.setForeground(new java.awt.Color(0, 102, 153));
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonZapamti, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 100, 30));

        jButtonOdustani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOdustani.setForeground(new java.awt.Color(0, 102, 153));
        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Organizacija:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 50));
        jPanel1.add(jTextFieldOrganizacija, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 428, 29));

        jButtonPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPromeni.setText("Promeni kvalifikaciju");
        jButtonPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, -1));

        jButtonPrikaziPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziPromeni.setText("Prikaži kvalifikaciju");
        jButtonPrikaziPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPromeniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, -1));

        jButtonObrisiKvalifikaciju.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisiKvalifikaciju.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisiKvalifikaciju.setText("Obriši kvalifikaciju");
        jButtonObrisiKvalifikaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiKvalifikacijuActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonObrisiKvalifikaciju, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        jButtonPrikaziObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziObrisi.setText("Prikaži kvalifikaciju");
        jButtonPrikaziObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziObrisiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 680, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTipActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonPrikaziPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPromeniActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziPromeniActionPerformed

    private void jButtonPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPromeniActionPerformed

    private void jButtonObrisiKvalifikacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiKvalifikacijuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonObrisiKvalifikacijuActionPerformed

    private void jButtonPrikaziObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziObrisiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziObrisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonObrisiKvalifikaciju;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPrikaziObrisi;
    private javax.swing.JButton jButtonPrikaziPromeni;
    private javax.swing.JButton jButtonPromeni;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldOrganizacija;
    private javax.swing.JTextField jTextFieldTip;
    // End of variables declaration//GEN-END:variables

    public void ZapamtiAddActionListeners(ActionListener actionListener) {
        jButtonZapamti.addActionListener(actionListener);
    }

    public void PromeniAddActionListeners(ActionListener actionListener) {
        jButtonSacuvaj.addActionListener(actionListener);
    }

    public void ObrisiAddActionListeners(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }

    public void OdustaniAddActionListeners(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }

    public void PrikaziPromeniAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziPromeni.addActionListener(actionListener);
    }

    public void ObrisiKvalifikacijuAddActionListeners(ActionListener actionListener) {
        jButtonObrisiKvalifikaciju.addActionListener(actionListener);
    }

    public void PrikaziObrisiAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziObrisi.addActionListener(actionListener);
    }

    public void PromeniKvalifikacijuAddActionListeners(ActionListener actionListener) {
        jButtonPromeni.addActionListener(actionListener);
    }

}
