/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Nivo;
import model.Polaznik;
import model.Sertifikat;
import model.VrstaPlesa;

/**
 *
 * @author Tijana
 */
public class KreirajSertifikat extends javax.swing.JFrame {
    
    private GlavnaForma gf;
    private Sertifikat sertifikat;

    public Sertifikat getSertifikat() {
        return sertifikat;
    }

    public void setSertifikat(Sertifikat sertifikat) {
        this.sertifikat = sertifikat;
    }

    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    public JButton getjButtonObrisiSertifikat() {
        return jButtonObrisiSertifikat;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public JButton getjButtonPrikaziObrisi() {
        return jButtonPrikaziObrisi;
    }

    public JButton getjButtonPrikaziPromeni() {
        return jButtonPrikaziPromeni;
    }

    public JButton getjButtonPromeniSertifikat() {
        return jButtonPromeniSertifikat;
    }

    public JButton getjButtonSacuvaj() {
        return jButtonSacuvaj;
    }

    public JButton getjButtonZapamti() {
        return jButtonZapamti;
    }

    public JComboBox<Nivo> getjComboBoxNivo() {
        return jComboBoxNivo;
    }

    public JComboBox<Polaznik> getjComboBoxPolaznik() {
        return (JComboBox<Polaznik>) jComboBoxPolaznik;
    }

    public JComboBox<VrstaPlesa> getjComboBoxVrstaPlesa() {
        return (JComboBox<VrstaPlesa>) jComboBoxVrstaPlesa;
    }

    public JTextField getjTextFieldDatumIzdavanja() {
        return jTextFieldPrezime3;
    }

    public JTextField getjTextFieldMestoIzdavanja() {
        return jTextFieldPrezime1;
    }

    public JTextField getjTextFieldNapomena() {
        return jTextFieldPrezime2;
    }

    /**
     * Creates new form KreirajSertifikat
     */
   public KreirajSertifikat(java.awt.Frame parent, boolean modal, Sertifikat sertifikat) {
        super();
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(800, 370);
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Kreiraj sertifikat");
        this.gf = (GlavnaForma) parent;
        this.sertifikat = sertifikat;

        jComboBoxNivo.removeAllItems();
        for (Nivo n : Nivo.values()) {
            jComboBoxNivo.addItem(n);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxNivo = new javax.swing.JComboBox<>();
        jComboBoxVrstaPlesa = new javax.swing.JComboBox<>();
        jTextFieldPrezime1 = new javax.swing.JTextField();
        jTextFieldPrezime2 = new javax.swing.JTextField();
        jTextFieldPrezime3 = new javax.swing.JTextField();
        jComboBoxPolaznik = new javax.swing.JComboBox<>();
        jButtonPromeniSertifikat = new javax.swing.JButton();
        jButtonObrisiSertifikat = new javax.swing.JButton();
        jButtonPrikaziPromeni = new javax.swing.JButton();
        jButtonPrikaziObrisi = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mesto izdavanja:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datum izdavanja: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Polaznik:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nivo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 37, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Napomena:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vrsta plesa:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, 30));

        jComboBoxNivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNivoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 190, 30));

        jComboBoxVrstaPlesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVrstaPlesaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxVrstaPlesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 230, 30));
        getContentPane().add(jTextFieldPrezime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 190, 29));
        getContentPane().add(jTextFieldPrezime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, 29));
        getContentPane().add(jTextFieldPrezime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 190, 29));

        jComboBoxPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPolaznikActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPolaznik, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 230, 30));

        jButtonPromeniSertifikat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPromeniSertifikat.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPromeniSertifikat.setText("Promeni sertifikat");
        jButtonPromeniSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniSertifikatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPromeniSertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 30));

        jButtonObrisiSertifikat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisiSertifikat.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisiSertifikat.setText("Obriši sertifikat");
        jButtonObrisiSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiSertifikatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonObrisiSertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 30));

        jButtonPrikaziPromeni.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziPromeni.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziPromeni.setText("Prikaži sertifikat");
        jButtonPrikaziPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPromeniActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrikaziPromeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 30));

        jButtonPrikaziObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziObrisi.setText("Prikaži sertifikat");
        jButtonPrikaziObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrikaziObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 30));

        jButtonSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 153));
        jButtonSacuvaj.setText("Sačuvaj promene");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 30));

        jButtonZapamti.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonZapamti.setForeground(new java.awt.Color(0, 102, 153));
        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonZapamti, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 30));

        jButtonObrisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonObrisi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonObrisi.setText("Obriši");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonObrisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 140, 30));

        jButtonOdustani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOdustani.setForeground(new java.awt.Color(0, 102, 153));
        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SERTIFIKAT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNivoActionPerformed

    private void jComboBoxVrstaPlesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVrstaPlesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVrstaPlesaActionPerformed

    private void jComboBoxPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPolaznikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPolaznikActionPerformed

    private void jButtonPromeniSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniSertifikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPromeniSertifikatActionPerformed

    private void jButtonObrisiSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiSertifikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonObrisiSertifikatActionPerformed

    private void jButtonPrikaziPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPromeniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziPromeniActionPerformed

    private void jButtonPrikaziObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziObrisiActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonObrisiSertifikat;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonPrikaziObrisi;
    private javax.swing.JButton jButtonPrikaziPromeni;
    private javax.swing.JButton jButtonPromeniSertifikat;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JComboBox<model.Nivo> jComboBoxNivo;
    private javax.swing.JComboBox<Polaznik> jComboBoxPolaznik;
    private javax.swing.JComboBox<VrstaPlesa> jComboBoxVrstaPlesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldPrezime;
    private javax.swing.JTextField jTextFieldPrezime1;
    private javax.swing.JTextField jTextFieldPrezime2;
    private javax.swing.JTextField jTextFieldPrezime3;
    // End of variables declaration//GEN-END:variables

    public void ZapamtiAddActionListeners(ActionListener actionListener) {
        jButtonZapamti.addActionListener(actionListener);
    }

    public void PromeniAddActionListeners(ActionListener actionListener) {
        jButtonSacuvaj.addActionListener(actionListener);
    }

    public void ObrisiAddActionListeners(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }

    public void OdustaniAddActionListeners(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }

    public void PromeniSertifikatAddActionListeners(ActionListener actionListener) {
        jButtonPromeniSertifikat.addActionListener(actionListener);
    }

    public void ObrisiSertifikatAddActionListeners(ActionListener actionListener) {
        jButtonObrisiSertifikat.addActionListener(actionListener);
    }

    public void PrikaziPromeniAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziPromeni.addActionListener(actionListener);
    }

    public void PrikaziObrisiAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziObrisi.addActionListener(actionListener);
    }

}
