/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import model.Kvalifikacija;

/**
 *
 * @author Tijana
 */
public class PretraziInstruktora extends javax.swing.JDialog {

    private GlavnaForma gf;

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    public JButton getjButtonPrikazi() {
        return jButtonPrikazi;
    }

    public void setjButtonPrikazi(JButton jButtonPrikazi) {
        this.jButtonPrikazi = jButtonPrikazi;
    }

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public void setjButtonPrikaziSve(JButton jButtonPrikaziSve) {
        this.jButtonPrikaziSve = jButtonPrikaziSve;
    }

    public JComboBox<Kvalifikacija> getjComboBoxKvalifikacija() {
        return jComboBoxKvalifikacija;
    }

    public void setjComboBoxKvalifikacija(JComboBox<Kvalifikacija> jComboBoxKvalifikacija) {
        this.jComboBoxKvalifikacija = jComboBoxKvalifikacija;
    }

    public JRadioButton getjRadioButtonID() {
        return jRadioButtonID;
    }

    public void setjRadioButtonID(JRadioButton jRadioButtonID) {
        this.jRadioButtonID = jRadioButtonID;
    }

    public JRadioButton getjRadioButtonKvalifikacija() {
        return jRadioButtonKvalifikacija;
    }

    public void setjRadioButtonKvalifikacija(JRadioButton jRadioButtonKvalifikacija) {
        this.jRadioButtonKvalifikacija = jRadioButtonKvalifikacija;
    }

    public JTable getjTableInstruktori() {
        return jTableInstruktori;
    }

    public void setjTableInstruktori(JTable jTableInstruktori) {
        this.jTableInstruktori = jTableInstruktori;
    }

    public JTextField getjTextFieldInstruktor() {
        return jTextFieldInstruktor;
    }

    public void setjTextFieldInstruktor(JTextField jTextFieldInstruktor) {
        this.jTextFieldInstruktor = jTextFieldInstruktor;
    }

    /**
     * Creates new form PretraziInstruktora
     *
     * @param parent
     * @param modal
     */
    public PretraziInstruktora(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(914, 656);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Pretraži instruktora");

        this.gf = (GlavnaForma) parent;

        jTableInstruktori.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row % 2 == 0) {

                        cell.setBackground(Color.WHITE);

                    } else {
                        cell.setBackground(new Color(204, 255, 255));
                    }
                }
                if (isSelected) {
                    cell.setBackground(new Color(204, 204, 204));
                }

                cell.setForeground(new Color(0, 102, 153));
                return cell;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInstruktori = new javax.swing.JTable();
        jButtonPrikazi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxKvalifikacija = new javax.swing.JComboBox<>();
        jTextFieldInstruktor = new javax.swing.JTextField();
        jButtonPrikaziSve = new javax.swing.JButton();
        jRadioButtonKvalifikacija = new javax.swing.JRadioButton();
        jRadioButtonID = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonPretrazi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTRUKTORI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        jTableInstruktori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableInstruktori.setRowHeight(25);
        jTableInstruktori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableInstruktori.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableInstruktori.setShowGrid(false);
        jTableInstruktori.getTableHeader().setResizingAllowed(false);
        jTableInstruktori.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableInstruktori);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 870, 230));

        jButtonPrikazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikazi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikazi.setText("Prikaži instruktora");
        jButtonPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 140, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prikaži sve instruktore:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filtriraj instruktore po kvalifikaciji:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 263, -1));

        jComboBoxKvalifikacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxKvalifikacijaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxKvalifikacija, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 560, -1));
        jPanel1.add(jTextFieldInstruktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, -1));

        jButtonPrikaziSve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziSve.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziSve.setText("Prikaži");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPrikaziSve, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 136, -1));

        jRadioButtonKvalifikacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKvalifikacijaActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonKvalifikacija, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jRadioButtonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIDActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtriraj instruktore po imenu i prezimenu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 280, -1));

        jButtonPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretrazi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 136, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pronađeni instruktori");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziActionPerformed

    private void jRadioButtonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonIDActionPerformed

    private void jRadioButtonKvalifikacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKvalifikacijaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonKvalifikacijaActionPerformed

    private void jComboBoxKvalifikacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxKvalifikacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxKvalifikacijaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPrikazi;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JComboBox<Kvalifikacija> jComboBoxKvalifikacija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonKvalifikacija;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInstruktori;
    private javax.swing.JTextField jTextFieldInstruktor;
    // End of variables declaration//GEN-END:variables

    public void VratiListuSvihInstruktoraAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziSve.addActionListener(actionListener);
    }

    public void VratiListuInstruktoraSaUslovomAddActionListeners(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }

    public void PrikaziInstruktoraAddActionListeners(ActionListener actionListener) {
        jButtonPrikazi.addActionListener(actionListener);
    }

    public void RadioIDAddActionListeners(ActionListener actionListener) {
        jRadioButtonID.addActionListener(actionListener);
    }

    public void RadioKvalifikacijaAddActionListeners(ActionListener actionListener) {
        jRadioButtonKvalifikacija.addActionListener(actionListener);
    }

}
