/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Tijana
 */
public class PretraziVrstuPlesa extends javax.swing.JDialog {

    private GlavnaForma gf;

    public JButton getjButtonNadji() {
        return jButtonNadji;
    }

    public void setjButtonNadji(JButton jButtonNadji) {
        this.jButtonNadji = jButtonNadji;
    }

    public JButton getjButtonPretraziID() {
        return jButtonPretraziID;
    }

    public void setjButtonPretraziID(JButton jButtonPretraziID) {
        this.jButtonPretraziID = jButtonPretraziID;
    }

    public JButton getjButtonPretraziSve() {
        return jButtonPretraziSve;
    }

    public void setjButtonPretraziSve(JButton jButtonPretraziSve) {
        this.jButtonPretraziSve = jButtonPretraziSve;
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }

    public JTextField getjTextFieldKategorija() {
        return jTextFieldKategorija;
    }

    public void setjTextFieldKategorija(JTextField jTextFieldKategorija) {
        this.jTextFieldKategorija = jTextFieldKategorija;
    }

    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    /**
     * Creates new form pretraziVrstaPlesa
     * @param parent
     * @param modal
     */
    public PretraziVrstuPlesa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(747, 623);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Pretraži vrstu plesa");

        this.gf = (GlavnaForma) parent;

        jTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row % 2 == 0) {
                        cell.setBackground(Color.WHITE);
                    } else {
                        cell.setBackground(new Color(204, 255, 255));
                    }
                }

                if (isSelected) {
                    cell.setBackground(new Color(204, 204, 204));
                }

                cell.setForeground(new Color(0, 102, 153));

                return cell;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPretraziID = new javax.swing.JButton();
        jButtonPretraziSve = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButtonNadji = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jTextFieldKategorija = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtriraj vrstu plesa po nazivu i kategoriji: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 60));

        jButtonPretraziID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziID.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziID.setText("Pretraži");
        jButtonPretraziID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziIDActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretraziID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 130, -1));

        jButtonPretraziSve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziSve.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziSve.setText("Prikaži");
        jButtonPretraziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziSveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretraziSve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 135, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prikaži sve vrste plesa: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VRSTE PLESA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 210, 50));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setRowHeight(25);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 670, 240));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pronađene vrste plesa");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, -1));

        jButtonNadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNadji.setForeground(new java.awt.Color(0, 102, 153));
        jButtonNadji.setText("Prikaži vrstu plesa");
        jButtonNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 170, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kategorija:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Naziv:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jTextFieldNaziv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNazivActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 190, 27));

        jTextFieldKategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKategorijaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldKategorija, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 190, 27));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziIDActionPerformed

    private void jButtonPretraziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziSveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziSveActionPerformed

    private void jButtonNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonNadjiActionPerformed

    private void jTextFieldNazivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNazivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNazivActionPerformed

    private void jTextFieldKategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKategorijaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNadji;
    private javax.swing.JButton jButtonPretraziID;
    private javax.swing.JButton jButtonPretraziSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldKategorija;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    public void VratiListuSvihVrstaPlesaAddActionListeners(ActionListener actionListener) {
        jButtonPretraziSve.addActionListener(actionListener);
    }

    public void VratiListuVrstaPlesaSaUslovomAddActionListeners(ActionListener actionListener) {
        jButtonPretraziID.addActionListener(actionListener);
    }

    public void PrikaziVrstuPlesaAddActionListeners(ActionListener actionListener) {
        jButtonNadji.addActionListener(actionListener);
    }

}
