/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Tijana
 */
public class PretraziUzrasnuKategoriju extends javax.swing.JDialog {

    private GlavnaForma gf;

    public JButton getjButtonNadji() {
        return jButtonNadji;
    }

    public void setjButtonNadji(JButton jButtonNadji) {
        this.jButtonNadji = jButtonNadji;
    }

    public JButton getjButtonPretraziId() {
        return jButtonPretraziId;
    }

    public void setjButtonPretraziId(JButton jButtonPretraziId) {
        this.jButtonPretraziId = jButtonPretraziId;
    }

    public JButton getjButtonPretraziSVe() {
        return jButtonPretraziSVe;
    }

    public void setjButtonPretraziSVe(JButton jButtonPretraziSVe) {
        this.jButtonPretraziSVe = jButtonPretraziSVe;
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }

    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public void setjTextFieldNaziv(JTextField jTextFieldNaziv) {
        this.jTextFieldNaziv = jTextFieldNaziv;
    }

    public JTextField getjTextFieldOpsegGodina() {
        return jTextFieldOpsegGodina;
    }

    public void setjTextFieldOpsegGodina(JTextField jTextFieldOpsegGodina) {
        this.jTextFieldOpsegGodina = jTextFieldOpsegGodina;
    }

    /**
     * Creates new form PretraziUzrast
     * @param parent
     * @param modal
     */
    public PretraziUzrasnuKategoriju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(714, 631);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Pretraži uzrasnu kategoriju");

        this.gf = (GlavnaForma) parent;

        jTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row % 2 == 0) {
                        cell.setBackground(Color.WHITE);
                    } else {
                        cell.setBackground(new Color(204, 255, 255));
                    }
                }
                if (isSelected) {
                    cell.setBackground(new Color(204, 204, 204));
                }

                cell.setForeground(new Color(0, 102, 153));

                return cell;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonNadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPretraziSVe = new javax.swing.JButton();
        jButtonPretraziId = new javax.swing.JButton();
        jTextFieldOpsegGodina = new javax.swing.JTextField();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("UZRASNE KATEGORIJE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 33, 260, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNadji.setForeground(new java.awt.Color(0, 102, 153));
        jButtonNadji.setText("Prikaži uzrasnu kategoriju");
        jButtonNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, 190, 30));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setRowHeight(25);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 660, 250));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pronađene uzrasne kategorije");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 290, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtriraj uzrasne kategorije po godinama i nazivu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 330, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prikaži sve uzrasne kategorije:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 140));

        jButtonPretraziSVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziSVe.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziSVe.setText("Prikaži");
        jButtonPretraziSVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziSVeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretraziSVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 110, -1));

        jButtonPretraziId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziId.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziId.setText("Pretraži");
        jButtonPretraziId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziIdActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretraziId, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, -1));
        jPanel1.add(jTextFieldOpsegGodina, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 160, 27));
        jPanel1.add(jTextFieldNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 160, 27));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Naziv:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Opseg godina:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziIdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziIdActionPerformed

    private void jButtonNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonNadjiActionPerformed

    private void jButtonPretraziSVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziSVeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziSVeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNadji;
    private javax.swing.JButton jButtonPretraziId;
    private javax.swing.JButton jButtonPretraziSVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldOpsegGodina;
    // End of variables declaration//GEN-END:variables

    public void VratiListuSvihUzrasnihKategorijaAddActionListeners(ActionListener actionListener) {
        jButtonPretraziSVe.addActionListener(actionListener);
    }

    public void VratiListuUzrasnihKategorijaSaUslovomAddActionListeners(ActionListener actionListener) {
        jButtonPretraziId.addActionListener(actionListener);
    }

    public void PrikaziUzrasnuKategorijuAddActionListeners(ActionListener actionListener) {
        jButtonNadji.addActionListener(actionListener);
    }

}
