/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import model.VrstaPlesa;
import model.Polaznik;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import model.ModelTabeleSertifikat;

/**
 *
 * @author Tijana
 */
public class PretraziSertifikat extends javax.swing.JFrame {

    /**
     * Creates new form PretraziSertifikat
     */
   public PretraziSertifikat(java.awt.Frame parent, boolean modal) {
    super();
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | javax.swing.UnsupportedLookAndFeelException ex) {
        System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
    }
    initComponents();
    this.setSize(780, 620);
    this.setLocationRelativeTo(null);
    setResizable(false);
    this.setTitle("Pretraži sertifikate");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonPretraziSVe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonPolaznik = new javax.swing.JRadioButton();
        jRadioButtonPolaznik1 = new javax.swing.JRadioButton();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSertifikati = new javax.swing.JTable();
        jButtonPrikaziSertifikat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPolaznik = new javax.swing.JComboBox<>();
        jComboBoxVrstaPlesa = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prikaži sve sertifikate:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 250, 70));

        jButtonPretraziSVe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziSVe.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziSVe.setText("Prikaži");
        jButtonPretraziSVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziSVeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPretraziSVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Filtriraj sertifikate po vrsti plesa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 220, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filtriraj sertifikate po polazniku:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 330, 30));

        jRadioButtonPolaznik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolaznikActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPolaznik, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 30));

        jRadioButtonPolaznik1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPolaznik1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPolaznik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        jButtonPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretrazi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPretrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 140, 30));

        jTableSertifikati.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableSertifikati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSertifikati.setRowHeight(25);
        jTableSertifikati.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSertifikati.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableSertifikati.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSertifikati);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 710, 232));

        jButtonPrikaziSertifikat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziSertifikat.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziSertifikat.setText("Prikaži sertifikat");
        jButtonPrikaziSertifikat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSertifikatActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPrikaziSertifikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 139, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SERTIFIKATI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 119, 60));

        getContentPane().add(jComboBoxPolaznik, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 240, 30));

        getContentPane().add(jComboBoxVrstaPlesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziSVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziSVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPretraziSVeActionPerformed

    private void jRadioButtonPolaznikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolaznikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPolaznikActionPerformed

    private void jRadioButtonPolaznik1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPolaznik1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPolaznik1ActionPerformed

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonPrikaziSertifikatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSertifikatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrikaziSertifikatActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPretraziSVe;
    private javax.swing.JButton jButtonPrikaziSertifikat;
    private javax.swing.JComboBox<Polaznik> jComboBoxPolaznik;
    private javax.swing.JComboBox<VrstaPlesa> jComboBoxVrstaPlesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonPolaznik;
    private javax.swing.JRadioButton jRadioButtonPolaznik1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSertifikati;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getjTable() {
    return jTableSertifikati;
}

public javax.swing.JComboBox<Polaznik> getjComboBoxPolaznik() {
    return jComboBoxPolaznik;
}

public javax.swing.JComboBox<VrstaPlesa> getjComboBoxVrstaPlesa() {
    return jComboBoxVrstaPlesa;
}

public javax.swing.JRadioButton getjRadioButtonPolaznik() {
    return jRadioButtonPolaznik;
}

public javax.swing.JRadioButton getjRadioButtonVrstaPlesa() {
    return jRadioButtonPolaznik1;
}

public void VratiListuSvihSertifikataAddActionListeners(java.awt.event.ActionListener actionListener) {
    jButtonPretraziSVe.addActionListener(actionListener);
}

public void PretraziAddActionListeners(java.awt.event.ActionListener actionListener) {
    jButtonPretrazi.addActionListener(actionListener);
}

public void PrikaziSertifikatAddActionListeners(java.awt.event.ActionListener actionListener) {
    jButtonPrikaziSertifikat.addActionListener(actionListener);
}

public void RadioPolaznikAddActionListeners(java.awt.event.ActionListener actionListener) {
    jRadioButtonPolaznik.addActionListener(actionListener);
}

public void RadioVrstaPlesaAddActionListeners(java.awt.event.ActionListener actionListener) {
    jRadioButtonPolaznik1.addActionListener(actionListener);
}

public void popuniTabelu() {
    ModelTabeleSertifikat modelTabele = new ModelTabeleSertifikat(new ArrayList<>());
    jTableSertifikati.setModel(modelTabele);
}
}
