/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Tijana
 */
public class PretraziKvalifkaciju extends javax.swing.JDialog {

    private GlavnaForma gf;

    public JButton getjButtonNadji() {
        return jButtonNadji;
    }

    public void setjButtonNadji(JButton jButtonNadji) {
        this.jButtonNadji = jButtonNadji;
    }

    public JButton getjButtonPretraziID() {
        return jButtonPretraziID;
    }

    public void setjButtonPretraziID(JButton jButtonPretraziID) {
        this.jButtonPretraziID = jButtonPretraziID;
    }

    public JButton getjButtonPrikaziSve() {
        return jButtonPrikaziSve;
    }

    public void setjButtonPrikaziSve(JButton jButtonPrikaziSve) {
        this.jButtonPrikaziSve = jButtonPrikaziSve;
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }

    public JTextField getjTextFieldOrganizacija() {
        return jTextFieldOrganizacija;
    }

    public void setjTextFieldOrganizacija(JTextField jTextFieldOrganizacija) {
        this.jTextFieldOrganizacija = jTextFieldOrganizacija;
    }

    public JTextField getjTextFieldTip() {
        return jTextFieldTip;
    }

    public void setjTextFieldTip(JTextField jTextFieldTip) {
        this.jTextFieldTip = jTextFieldTip;
    }

    /**
     * Creates new form PretraziKvalifkacija
     *
     * @param parent
     * @param modal
     */
    public PretraziKvalifkaciju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(942, 645);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Pretraži kvalifikaciju");

        this.gf = (GlavnaForma) parent;

        jTable.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row % 2 == 0) {
                        cell.setBackground(Color.WHITE);
                    } else {
                        cell.setBackground(new Color(204, 255, 255));
                    }
                }
                if (isSelected) {
                    cell.setBackground(new Color(204, 204, 204));
                }

                cell.setForeground(new Color(0, 102, 153));

                return cell;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonPrikaziSve = new javax.swing.JButton();
        jButtonPretraziID = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonNadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jTextFieldTip = new javax.swing.JTextField();
        jTextFieldOrganizacija = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KVALIFIKACIJE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prikaži sve kvalifikacije: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Filtriraj kvalifikacije po tipu i organizaciji:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, 30));

        jButtonPrikaziSve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPrikaziSve.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPrikaziSve.setText("Prikaži");
        jButtonPrikaziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziSveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPrikaziSve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, -1));

        jButtonPretraziID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziID.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziID.setText("Pretraži");
        jButtonPretraziID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziIDActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPretraziID, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pronađene kvalifikacije");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, -1));

        jButtonNadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNadji.setForeground(new java.awt.Color(0, 102, 153));
        jButtonNadji.setText("Prikaži kvalifikaciju");
        jButtonNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 560, 160, 30));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setRowHeight(25);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 850, 254));
        jPanel2.add(jTextFieldTip, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 280, 27));

        jTextFieldOrganizacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOrganizacijaActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldOrganizacija, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 280, 27));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tip:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Organizacija:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrikaziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziSveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPrikaziSveActionPerformed

    private void jButtonPretraziIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziIDActionPerformed

    private void jButtonNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonNadjiActionPerformed

    private void jTextFieldOrganizacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOrganizacijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOrganizacijaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNadji;
    private javax.swing.JButton jButtonPretraziID;
    private javax.swing.JButton jButtonPrikaziSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldOrganizacija;
    private javax.swing.JTextField jTextFieldTip;
    // End of variables declaration//GEN-END:variables

    public void VratiListuSvihKvalifikacijaAddActionListeners(ActionListener actionListener) {
        jButtonPrikaziSve.addActionListener(actionListener);
    }

    public void VratiListuKvalifikacijaSaUslovomAddActionListeners(ActionListener actionListener) {
        jButtonPretraziID.addActionListener(actionListener);
    }

    public void PrikaziKvalifikacijuAddActionListeners(ActionListener actionListener) {
        jButtonNadji.addActionListener(actionListener);
    }

}
