/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Tijana
 */
public class PretraziPolaznika extends javax.swing.JDialog {

    private GlavnaForma gf;

    public JButton getjButtonNadji() {
        return jButtonNadji;
    }

    public void setjButtonNadji(JButton jButtonNadji) {
        this.jButtonNadji = jButtonNadji;
    }

    public JButton getjButtonPretrazi() {
        return jButtonPretrazi;
    }

    public void setjButtonPretrazi(JButton jButtonPretrazi) {
        this.jButtonPretrazi = jButtonPretrazi;
    }

    public JButton getjButtonPretraziSve() {
        return jButtonPretraziSve;
    }

    public void setjButtonPretraziSve(JButton jButtonPretraziSve) {
        this.jButtonPretraziSve = jButtonPretraziSve;
    }

    public JRadioButton getjRadioButtonID() {
        return jRadioButtonID;
    }

    public void setjRadioButtonID(JRadioButton jRadioButtonID) {
        this.jRadioButtonID = jRadioButtonID;
    }

    public JRadioButton getjRadioButtonUzrast() {
        return jRadioButtonUzrast;
    }

    public void setjRadioButtonUzrast(JRadioButton jRadioButtonUzrast) {
        this.jRadioButtonUzrast = jRadioButtonUzrast;
    }

    public JTable getjTablePolaznici() {
        return jTablePolaznici;
    }

    public void setjTablePolaznici(JTable jTablePolaznici) {
        this.jTablePolaznici = jTablePolaznici;
    }

    public JTextField getjTextFieldPolaznik() {
        return jTextFieldPolaznik;
    }

    public void setjTextFieldPolaznik(JTextField jTextFieldPolaznik) {
        this.jTextFieldPolaznik = jTextFieldPolaznik;
    }

    public JTextField getjTextFieldUzrast() {
        return jTextFieldUzrast;
    }

    public void setjTextFieldUzrast(JTextField jTextFieldUzrast) {
        this.jTextFieldUzrast = jTextFieldUzrast;
    }

    /**
     * Creates new form PretraziPolaznik
     *
     * @param parent
     * @param modal
     */
    public PretraziPolaznika(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }
        initComponents();
        this.setSize(1026, 650);
        this.setLocationRelativeTo(null);

        setResizable(false);
        this.setTitle("Pretraži polaznika");

        this.gf = (GlavnaForma) parent;

        jTablePolaznici.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component cell = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row % 2 == 0) {
                        cell.setBackground(Color.WHITE);
                    } else {
                        cell.setBackground(new Color(204, 255, 255));
                    }
                }
                if (isSelected) {
                    cell.setBackground(new Color(204, 204, 204));
                }

                cell.setForeground(new Color(0, 102, 153));

                return cell;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonUzrast = new javax.swing.JRadioButton();
        jRadioButtonID = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUzrast = new javax.swing.JTextField();
        jTextFieldPolaznik = new javax.swing.JTextField();
        jButtonPretraziSve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePolaznici = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonNadji = new javax.swing.JButton();
        jButtonPretrazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Filtriraj polaznike po uzrasnoj kategoriji:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 280, 60));

        jRadioButtonUzrast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUzrastActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonUzrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 40));

        jRadioButtonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIDActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filtriraj polaznike po imenu i prezimenu:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prikaži sve polaznike:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 90, 150, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POLAZNICI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));
        jPanel1.add(jTextFieldUzrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 250, -1));
        jPanel1.add(jTextFieldPolaznik, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 250, -1));

        jButtonPretraziSve.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretraziSve.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretraziSve.setText("Prikaži");
        jButtonPretraziSve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziSveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretraziSve, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 129, -1));

        jTablePolaznici.setForeground(new java.awt.Color(0, 102, 153));
        jTablePolaznici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePolaznici.setRowHeight(25);
        jTablePolaznici.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePolaznici.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTablePolaznici.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePolaznici);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 950, 230));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pronađeni polaznici");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 170, -1));

        jButtonNadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonNadji.setForeground(new java.awt.Color(0, 102, 153));
        jButtonNadji.setText("Prikaži polaznika");
        jButtonNadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNadjiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNadji, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 129, 30));

        jButtonPretrazi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPretrazi.setForeground(new java.awt.Color(0, 102, 153));
        jButtonPretrazi.setText("Pretraži");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPretrazi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 129, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonNadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNadjiActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonNadjiActionPerformed

    private void jRadioButtonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonIDActionPerformed

    private void jRadioButtonUzrastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUzrastActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRadioButtonUzrastActionPerformed

    private void jButtonPretraziSveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziSveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonPretraziSveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNadji;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPretraziSve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonID;
    private javax.swing.JRadioButton jRadioButtonUzrast;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePolaznici;
    private javax.swing.JTextField jTextFieldPolaznik;
    private javax.swing.JTextField jTextFieldUzrast;
    // End of variables declaration//GEN-END:variables

    public void VratiListuSvihPolaznikaAddActionListeners(ActionListener actionListener) {
        jButtonPretraziSve.addActionListener(actionListener);
    }

    public void VratiListuPolaznikaSaUslovomAddActionListeners(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }

    public void PrikaziPolaznikaAddActionListeners(ActionListener actionListener) {
        jButtonNadji.addActionListener(actionListener);
    }

    public void RadioUzrastAddActionListeners(ActionListener actionListener) {
        jRadioButtonUzrast.addActionListener(actionListener);
    }

    public void RadioIDAddActionListeners(ActionListener actionListener) {
        jRadioButtonID.addActionListener(actionListener);
    }
}
