/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import konfiguracija.Konfiguracija;

/**
 *
 * @author Tijana
 */
public class FormaKonfiguracija extends javax.swing.JDialog {

    private boolean ispravniPodaci = true;

    public boolean isIspravniPodaci() {
        return ispravniPodaci;
    }

    public void setIspravniPodaci(boolean ispravniPodaci) {
        this.ispravniPodaci = ispravniPodaci;
    }

    public JLabel getjLabelKorisnik() {
        return jLabelKorisnik;
    }

    public void setjLabelKorisnik(JLabel jLabelKorisnik) {
        this.jLabelKorisnik = jLabelKorisnik;
    }

    public JLabel getjLabelLozinka() {
        return jLabelLozinka;
    }

    public void setjLabelLozinka(JLabel jLabelLozinka) {
        this.jLabelLozinka = jLabelLozinka;
    }

    public JLabel getjLabelPort() {
        return jLabelPort;
    }

    public void setjLabelPort(JLabel jLabelPort) {
        this.jLabelPort = jLabelPort;
    }

    public JLabel getjLabelURL() {
        return jLabelURL;
    }

    public void setjLabelURL(JLabel jLabelURL) {
        this.jLabelURL = jLabelURL;
    }

    /**
     * Creates new form Konfiguracija
     * @param parent
     * @param modal
     */
    public FormaKonfiguracija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }

        initComponents();

        this.setTitle("Konfiguracija");
        this.setLocationRelativeTo(null);
        this.setSize(540, 320);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelLozinka = new javax.swing.JLabel();
        jLabelKorisnik = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jLabelURL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Port:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 46, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("URL:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 107, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Korisnik:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 169, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lozinka:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 229, 80, -1));

        jLabelLozinka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelLozinka.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 229, 400, 25));

        jLabelKorisnik.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelKorisnik.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelKorisnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 169, 400, 25));

        jLabelPort.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPort.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 46, 400, 25));

        jLabelURL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelURL.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabelURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 107, 400, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelKorisnik;
    private javax.swing.JLabel jLabelLozinka;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    void unesiPodatke() {
        
        String port = Konfiguracija.getInstance().ucitajPodatak("Port");
        if (port == null) {
            jLabelPort.setText("Neispravan broj porta.");
            jLabelPort.setForeground(Color.RED);
        } else {
            jLabelPort.setText(port.trim());
        }
        String korisnik = Konfiguracija.getInstance().ucitajPodatak("Korisnik");
        String lozinka = Konfiguracija.getInstance().ucitajPodatak("Lozinka");
        String url = Konfiguracija.getInstance().ucitajPodatak("URL");

        jLabelURL.setText(url.trim());
        jLabelKorisnik.setText(korisnik.trim());
        jLabelLozinka.setText(lozinka.trim());

    }

    boolean proveriPodatke() {

        String portText = jLabelPort.getText();
        String url = jLabelURL.getText();
        String korisnik = jLabelKorisnik.getText();
        int port;

        if (portText.trim().isEmpty() || portText.trim().equals("N/A") || korisnik.trim().isEmpty() || korisnik.trim().equals("N/A") || url.trim().isEmpty() || url.trim().equals("N/A")) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }
        try {
            port = Integer.parseInt(portText);
        } catch (NumberFormatException numberFormatException) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }
        if (port < 0 || port > 65536) {
            ispravniPodaci = false;
            return ispravniPodaci;
        }

        return ispravniPodaci;
    }

}
