/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tijana
 */
public class FormaKreirajKonfiguraciju extends javax.swing.JDialog {

    private ServerskaForma parent;

    /**
     * Creates new form FormaKreirajKonfiguracije
     *
     * @param parent
     * @param modal
     */
    public FormaKreirajKonfiguraciju(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            System.err.println("Greška prilikom postavljanja Nimbus dizajna: " + ex.getMessage());
        }

        initComponents();

        this.parent = (ServerskaForma) parent;

        this.setTitle("Kreiraj konfiguracije");
        this.setLocationRelativeTo(null);
        this.setSize(540, 380);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldKorisnik = new javax.swing.JTextField();
        jTextFieldLozinka = new javax.swing.JTextField();
        jTextFieldUrl = new javax.swing.JTextField();
        jButtonOdustani = new javax.swing.JButton();
        jButtonSacuvaj = new javax.swing.JButton();
        jTextFieldPort = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lozinka:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Korisnik:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("URL:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Port:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, -1, 30));
        jPanel1.add(jTextFieldKorisnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 310, 29));
        jPanel1.add(jTextFieldLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 310, 29));
        jPanel1.add(jTextFieldUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 310, 29));

        jButtonOdustani.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonOdustani.setForeground(new java.awt.Color(0, 102, 153));
        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonOdustani, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 100, 30));

        jButtonSacuvaj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSacuvaj.setForeground(new java.awt.Color(0, 102, 153));
        jButtonSacuvaj.setText("Sačuvaj");
        jButtonSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacuvajActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSacuvaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 100, 30));
        jPanel1.add(jTextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 310, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da odustanete od unosa podataka o konfiguraciji?", "Potvrda", JOptionPane.YES_NO_OPTION);
        if (odgovor == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacuvajActionPerformed
        // TODO add your handling code here:
        String portText = jTextFieldPort.getText().trim();
        String korisnik = jTextFieldKorisnik.getText().trim();
        String lozinka = jTextFieldLozinka.getText().trim();
        String url = jTextFieldUrl.getText().trim();

        jTextFieldPort.setText("");
        jTextFieldUrl.setText("");
        jTextFieldKorisnik.setText("");
        jTextFieldLozinka.setText("");

        int port;

        if (portText.trim().isEmpty() || korisnik.trim().isEmpty() || url.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli sve podatke.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            port = Integer.parseInt(portText);
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Niste uneli broj porta u ispravnom formatu.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (port < 0 || port > 65536) {
            JOptionPane.showMessageDialog(this, "Niste uneli broj porta u okviru dozvoljenog opsega (0-65535).", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String putanja = "konfiguracija/Konfiguracija_server.properties";

        Properties podaci = new Properties();

        podaci.setProperty("Port", String.valueOf(port));
        podaci.setProperty("URL", url);
        podaci.setProperty("Korisnik", korisnik);
        podaci.setProperty("Lozinka", lozinka);

        try (FileOutputStream outputStream = new FileOutputStream(putanja)) {
            podaci.store(outputStream, "Konfiguracija");
            JOptionPane.showMessageDialog(this, "Konfiguracioni fajl je kreiran na putanji: " + putanja, "Uspešno", JOptionPane.INFORMATION_MESSAGE);
            parent.azuriraj();
            this.dispose();
        } catch (IOException e) {
            System.err.println("Greška prilikom kreiranja konfiguracionog fajla: " + e.getMessage());
            JOptionPane.showMessageDialog(this, "Greška prilikom kreiranja konfiguracionog fajla.", "Neuspešno", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButtonSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldKorisnik;
    private javax.swing.JTextField jTextFieldLozinka;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldUrl;
    // End of variables declaration//GEN-END:variables

}
