/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author Tijana
 */
public enum Operacije implements Serializable {

    PRIJAVI_INSTRUKTOR,
    KREIRAJ_UPISNICA,
    VRATI_LISTU_SVI_INSTRUKTOR,
    VRATI_LISTU_SVI_POLAZNIK,
    PROMENI_UPISNICA,
    VRATI_LISTU_SVI_VRSTA_PLESA,
    VRATI_LISTU_UPISNICA_UPISNICA,
    VRATI_LISTU_UPISNICA_INSTRUKTOR,
    VRATI_LISTU_UPISNICA_POLAZNIK,
    VRATI_LISTU_UPISNICA_VRSTA_PLESA,
    VRATI_LISTU_SVI_UPISNICA,
    DODAJ_PRIJAVLJENOG,
    ODJAVI_SE,
    KREIRAJ_POLAZNIK,
    PROMENI_POLAZNIK,
    OBRISI_POLAZNIK,
    VRATI_LISTU_POLAZNIK_POLAZNIK,
    VRATI_LISTU_POLAZNIK_UZRASNA_KATEGORIJA,
    PROMENI_INSTRUKTOR,
    KREIRAJ_INSTRUKTOR,
    OBRISI_INSTRUKTOR,
    VRATI_LISTU_SVI_KVALIFIKACIJA,
    VRATI_LISTU_INSTRUKTOR_INSTRUKTOR,
    KREIRAJ_UZRASNA_KATEGORIJA,
    PROMENI_UZRASNA_KATEGORIJA,
    OBRISI_UZRASNA_KATEGORIJA,
    VRATI_LISTU_UZRASNA_KATEGORIJA_UZRASNA_KATEGORIJA,
    VRATI_LISTU_SVI_UZRASNA_KATEGORIJA,
    OBRISI_VRSTA_PLESA,
    PROMENI_VRSTA_PLESA,
    KREIRAJ_VRSTA_PLESA,
    VRATI_LISTU_INSTRUKTOR_KVALIFIKACIJA,
    VRATI_LISTU_VRSTA_PLESA_VRSTA_PLESA,
    OBRISI_KVALIFIKACIJA,
    PROMENI_KVALIFIKACIJA,
    UBACI_KVALIFIKACIJA,
    PRETRAZI_UPISNICA,
    PRETRAZI_INSTRUKTOR,
    PRETRAZI_POLAZNIK,
    PRETRAZI_VRSTA_PLESA,
    PRETRAZI_UZRASNA_KATEGORIJA,
    PRETRAZI_KVALIFIKACIJA,
    VRATI_LISTU_KVALIFIKACIJA_KVALIFIKACIJA;

}
